//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helseboka.Core.Resources.StringResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helseboka.Core.Resources.StringResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yy HH:mm.
        /// </summary>
        public static string AppLongDateTimeFormat {
            get {
                return ResourceManager.GetString("AppLongDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string AppointmentHomeCancelledStatus {
            get {
                return ResourceManager.GetString("AppointmentHomeCancelledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can book an appointment with your doctor, see your booked appointments and cancel them.{0}{0}Via Helseboka you can book an appointment with your doctor no matter where in the country you are. It only requires that your doctor has opened up for communication at helseboka.no. You don&apos;t need to pay a fee to Helseboka to use the service.{0}{0}Click on notifications in your phone&apos;s notification settings for appointment reminder..
        /// </summary>
        public static string AppointmentHomeHelpText {
            get {
                return ResourceManager.GetString("AppointmentHomeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add medication reminders from the Medicines page. See main menu at the bottom of the page..
        /// </summary>
        public static string AppointmentHomeNoAlarmPopupMessage {
            get {
                return ResourceManager.GetString("AppointmentHomeNoAlarmPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will get all the important messages..
        /// </summary>
        public static string AppointmentHomeNoAppointmentPopupMessage {
            get {
                return ResourceManager.GetString("AppointmentHomeNoAppointmentPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not confirmed.
        /// </summary>
        public static string AppointmentHomeNoDateExpired {
            get {
                return ResourceManager.GetString("AppointmentHomeNoDateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for video talk.
        /// </summary>
        public static string AppointmentLinkButtonText {
            get {
                return ResourceManager.GetString("AppointmentLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message from doctor.
        /// </summary>
        public static string AppointmentNoMessage {
            get {
                return ResourceManager.GetString("AppointmentNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string BasicInfoTitle {
            get {
                return ResourceManager.GetString("BasicInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can ask questions directly to the doctor&apos;s office and your doctor. Helseboka can communicate with all medical offices in Norway provided that the doctor&apos;s office has opened up for communication at helseboka.no..
        /// </summary>
        public static string ChatHomeHelpTitle {
            get {
                return ResourceManager.GetString("ChatHomeHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message has not been delivered to the doctor. Do you want to send the message again?.
        /// </summary>
        public static string ChatResendConfirmationMessage {
            get {
                return ResourceManager.GetString("ChatResendConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend message.
        /// </summary>
        public static string ChatResendConfirmationTitle {
            get {
                return ResourceManager.GetString("ChatResendConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string ChatStatusDelivered {
            get {
                return ResourceManager.GetString("ChatStatusDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ChatStatusError {
            get {
                return ResourceManager.GetString("ChatStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string ChatStatusReceived {
            get {
                return ResourceManager.GetString("ChatStatusReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string ChatStatusSent {
            get {
                return ResourceManager.GetString("ChatStatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        public static string DeleteProfileConfirmationButton {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the profile? It may still be retrieved upto 30 days..
        /// </summary>
        public static string DeleteProfileConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all content.
        /// </summary>
        public static string DeleteProfileConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search doctor or medical center....
        /// </summary>
        public static string DoctorSearchPlaceholder {
            get {
                return ResourceManager.GetString("DoctorSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only expect the messages to appear and you will receive a response if this is your GP or your private doctor..
        /// </summary>
        public static string DoctorSelectionHelpText {
            get {
                return ResourceManager.GetString("DoctorSelectionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not chosen any persons or organization to communicate with. Click in the field below to search for health personel..
        /// </summary>
        public static string DoctorSelectionSubtitleDisabled {
            get {
                return ResourceManager.GetString("DoctorSelectionSubtitleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the following doctor to communicate with. Tap the doctor&apos;s name to change..
        /// </summary>
        public static string DoctorSelectionSubtitleEnabled {
            get {
                return ResourceManager.GetString("DoctorSelectionSubtitleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops...
        /// </summary>
        public static string ErrorInfoTitle {
            get {
                return ResourceManager.GetString("ErrorInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string FeedbackMailAppSelectorTitle {
            get {
                return ResourceManager.GetString("FeedbackMailAppSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback from Helseboka user.
        /// </summary>
        public static string FeedbackMailSubject {
            get {
                return ResourceManager.GetString("FeedbackMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB: Please do not send sensitive information in this email!.
        /// </summary>
        public static string FeedbackPopupAlert {
            get {
                return ResourceManager.GetString("FeedbackPopupAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send us feedback about bugs or improvements to the email address {0}.
        /// </summary>
        public static string FeedbackPopupMessage {
            get {
                return ResourceManager.GetString("FeedbackPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei!.
        /// </summary>
        public static string FeedbackPopupTitle {
            get {
                return ResourceManager.GetString("FeedbackPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GeneralTextCancel {
            get {
                return ResourceManager.GetString("GeneralTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string GeneralTextContinue {
            get {
                return ResourceManager.GetString("GeneralTextContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mobile number.
        /// </summary>
        public static string MobilePhoneNumberPageErrorMessage {
            get {
                return ResourceManager.GetString("MobilePhoneNumberPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid phone number.
        /// </summary>
        public static string MobilePhoneNumberPageErrorMessageText {
            get {
                return ResourceManager.GetString("MobilePhoneNumberPageErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your mobile phone number in order to communicate with Helseboka. The number will be included in messages you send from Helseboka..
        /// </summary>
        public static string MobilePhoneNumberPageText {
            get {
                return ResourceManager.GetString("MobilePhoneNumberPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select doctor or office here....
        /// </summary>
        public static string NewChatSenderPlaceholder {
            get {
                return ResourceManager.GetString("NewChatSenderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To: .
        /// </summary>
        public static string NewChatSenderPrefix {
            get {
                return ResourceManager.GetString("NewChatSenderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicate directly with the doctor and doctor&apos;s office.
        /// </summary>
        public static string OnBoardingFirstTitle {
            get {
                return ResourceManager.GetString("OnBoardingFirstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to app.
        /// </summary>
        public static string OnBoardingGoToButton {
            get {
                return ResourceManager.GetString("OnBoardingGoToButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopp over intro.
        /// </summary>
        public static string OnBoardingNextButton {
            get {
                return ResourceManager.GetString("OnBoardingNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book an appointment with the doctor or the doctor&apos;s office.
        /// </summary>
        public static string OnBoardingSecondTitle {
            get {
                return ResourceManager.GetString("OnBoardingSecondTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an overview of your medicines and renew prescriptions.
        /// </summary>
        public static string OnBoardingThirdTitle {
            get {
                return ResourceManager.GetString("OnBoardingThirdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone number is missing.
        /// </summary>
        public static string PhoneNumberPopupTitle {
            get {
                return ResourceManager.GetString("PhoneNumberPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Salutation {
            get {
                return ResourceManager.GetString("Salutation", resourceCulture);
            }
        }
    }
}
